<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\TreePage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\Http\RequestHandlers\CreateMediaObjectModal;

/**
 * @var string $body
 * @var string $subject
 * @var string $title
 * @var string $brief
 * @var Tree   $tree
 */

?>

<div class="row">
    <div class="col-md-8 mx-auto">


        <h2><?= $title ?></h2>

        <form method="post">
            <table>
                <tr>
                    <th>
                        <label for="updated">
                            <?= I18N::translate('UTC date and time') ?>
                        </label>
                    </th>
                <tr>
                <tr>
                    <td>
                        <input type="datetime-local" id="updated" class="form-control" name="updated" size="120" dir="auto" autofocus value="<?= e($updated) ?>">
                    </td>
                </tr>
                <tr>
                    <th>
                        <label for="subject">
                            <?= I18N::translate('Title') ?>
                        </label>
                    </th>
                <tr>
                <tr>
                    <td>
                        <input required type="text" id="subject" class="form-control" name="subject" size="120" dir="auto" autofocus value="<?= e($subject) ?>">
                    </td>
                </tr>

                <tr>
                    <th>
                        <label for="Image" class="form-label"><?= I18N::translate('Photo (enter the name of the previously added media file)') ?></label>
                        <div class="col-sm-8 col-md-9 w-100">
                            <?= view('components/select-media', ['name' => 'obje-xref', 'tree' => $tree, 'media' => $media]) ?>
                        </div>
                    </th>
                <tr>
                <tr>
                    <th class="text-end">
                        <a href="#" data-wt-href="<?= e(route(CreateMediaObjectModal::class, ['tree' => $tree->name()])) ?>" data-bs-target="#wt-ajax-modal" data-bs-toggle="modal" data-bs-backdrop="static">
                            <?= I18N::translate('Add new media object') ?>
                            <span class="visually-hidden"><?= e($tree->title()) ?></span>
                        </a>

                    </th>
                <tr>

                <tr>
                    <th>
                        <label for="brief">
                            <?= I18N::translate('Description') ?>
                        </label>
                    </th>
                <tr>
                <tr>
                    <td>
                        <textarea id="brief" name="brief" maxlength="600" class="form-control" rows="6" dir="auto"><?= e($brief) ?></textarea>
                    </td>
                </tr>

                <tr>
                    <th>
                        <label for="body">
                            <?= I18N::translate('Content') ?>
                        </label>
                    </th>
                </tr>
                <tr>
                    <td>
                        <textarea id="body" name="body" class="html-edit form-control" rows="12" dir="auto"><?= e($body) ?></textarea>
                    </td>
                </tr>

                <tr>
                    <td>
                        <button class="btn btn-primary" type="submit">
                            <?= I18N::translate('save') ?>
                        </button>

                        <a class="btn btn-secondary" href="<?= e(route(TreePage::class, ['tree' => $tree->name()])) ?>">
                            <?= I18N::translate('cancel') ?>
                        </a>
                    </td>
                </tr>
            </table>


            <?= csrf_field() ?>
        </form>
    </div>
</div>

<script>
    function preview() {
        frame.src = URL.createObjectURL(event.target.files[0]);
    }

    function clearImage() {
        document.getElementById('formFile').value = null;
        frame.src = "";
    }
</script>

<?= view('modals/ajax') ?>