<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Http\RequestHandlers\TreePage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\Http\RequestHandlers\CreateMediaObjectModal;

/**
 * @var string $body
 * @var string $subject
 * @var string $title
 * @var string $brief
 * @var Tree   $tree
 */

?>

<div class="row">
    <div class="col-md-8 mx-auto">

        <h2><?php echo $title; ?></h2>

        <form method="post">
            <table>
                <tr>
                    <th>
                        <label for="updated">
                            <?php echo I18N::translate('UTC date and time'); ?>
                        </label>
                    </th>
                <tr>
                <tr>
                    <td>
                        <input type="datetime-local" id="updated" class="form-control" name="updated" size="120" dir="auto" autofocus value="<?php echo e($updated); ?>">
                    </td>
                </tr>
                <tr>
                    <th>
                        <label for="subject">
                            <?php echo I18N::translate('Title'); ?>
                        </label>
                    </th>
                <tr>
                <tr>
                    <td>
                        <input required type="text" id="subject" class="form-control" name="subject" size="120" dir="auto" autofocus value="<?php echo e($subject); ?>">
                    </td>
                </tr>

                <tr>
                    <th>
                        <label for="Image" class="form-label"><?php echo I18N::translate('Photo (enter the name of the previously added media file)'); ?></label>
                        <div class="col-sm-8 col-md-9 w-100">
                            <?php echo view('components/select-media', ['name' => 'obje-xref', 'tree' => $tree, 'media' => $media]); ?>
                        </div>
                    </th>
                <tr>
                <tr>
                    <th class="text-end">
                        <a href="#" data-wt-href="<?php echo e(route(CreateMediaObjectModal::class, ['tree' => $tree->name()])); ?>" data-bs-target="#wt-ajax-modal" data-bs-toggle="modal" data-bs-backdrop="static">
                            <?php echo I18N::translate('Add new media object'); ?>
                            <span class="visually-hidden"><?php echo e($tree->title()); ?></span>
                        </a>
                    </th>
                <tr>

                <tr>
                    <th>
                        <label for="brief">
                            <?php echo I18N::translate('Description'); ?>
                        </label>
                    </th>
                <tr>
                <tr>
                    <td>
                        <textarea id="brief" name="brief" maxlength="600" class="form-control" rows="6" dir="auto"><?php echo e($brief); ?></textarea>
                    </td>
                </tr>

                <tr>
                    <th>
                        <label for="body">
                            <?php echo I18N::translate('Content'); ?>
                        </label>
                    </th>
                </tr>
                <tr>
                    <td>
                        <textarea id="body" name="body" class="html-edit form-control" rows="12" dir="auto"><?php echo e($body); ?></textarea>
                    </td>
                </tr>

                <tr>
                    <td>
                        <button class="btn btn-primary" type="submit">
                            <?php echo I18N::translate('save'); ?>
                        </button>

                        <a class="btn btn-secondary" href="<?php echo e(route(TreePage::class, ['tree' => $tree->name()])); ?>">
                            <?php echo I18N::translate('cancel'); ?>
                        </a>
                    </td>
                </tr>
            </table>

            <?php echo csrf_field(); ?>
        </form>
    </div>
</div>

<script>
    function preview() {
        frame.src = URL.createObjectURL(event.target.files[0]);
    }

    function clearImage() {
        document.getElementById('formFile').value = null;
        frame.src = "";
    }
</script>

<?php echo view('modals/ajax'); ?>
