<div class="row">
    <div class="col-md-12 wt-main-blocks">
        <div class="card mb-4 wt-block wt-block-gedcom_news" id="block-150">
            <div class="card-header wt-block-header wt-block-header-gedcom_news">
            <h2 class="text-center">
    <?= $title ?>
</h2>
            </div>
                <div class="card-body wt-block-content wt-block-content-gedcom_news">
                    <?php 
                    echo view('modules/gedcom_news/list', [
                    'articles' => $articles,
                    'limit'    => 5,
                    'tree'     => $tree,
                    ]); ?>
                </div> 
        </div> 
    </div> 
</div> 
