<?php

namespace Tywed\Webtrees\Module\NewsMenu;

use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var Collection<int,object> $articles 
 * @var Tree $tree */ ?>

<div class="row">
    <div class="col-md-12 wt-main-blocks ">
        <div class="card mb-4 wt-block wt-block-gedcom_news" id="block-150">
            <div class="card-header wt-block-header wt-block-header-gedcom_news">

                <h2 class="wt-page-title text-center fw-bold">
                    <?php echo $title; ?>
                </h2>

                <div class="d-grid gap-2 d-md-flex justify-content-md-end mb-4">
                    <?php if (Auth::isManager($tree)) : ?>
                        <a class="btn btn-primary" href="<?php echo e(route('module', ['module' => $module_name, 'action' => 'EditNews', 'tree' => $tree->name()])); ?>">
                            <?php echo I18N::translate('Add a news article'); ?>
                        </a>
                    <?php endif; ?>
                </div>

                <?php if ($articles->isEmpty()) : ?>
                    <?php echo I18N::translate('No news articles have been submitted.'); ?>
                <?php endif; ?>

                <div class="row gx-5">
                    <?php foreach ($articles as $n => $article) : ?>
                        <div class="col-md-4 mb-4">
                            <a href="<?php echo e(route('module', ['module' => $module_name, 'action' => 'ShowNews', 'news_id' => $article->news_id, 'tree' => $tree->name()])); ?>">
                                <?php if (isset($article->media_id)) {
                                    echo $article->media_id->displayImage(400, 267, 'contain', ['class' => 'img-fluid shadow-2-strong rounded-2 w-100']);
                                } ?>
                            </a>
                        </div>

                        <div class="col-md-8 mb-4">
                            <?php if ($article->updated->format('Y-m-d H:i:s') >= date('Y-m-d H:i:s')) : ?>
                                <span class="badge bg-warning px-2 py-1 shadow-1-strong mb-3">
                                    <?php echo I18N::translate('Planned:'); ?> <?php echo view('components/datetime', ['timestamp' => $article->updated]); ?>
                                </span>
                            <?php else : ?>
                                <span class="badge bg-primary px-2 py-1 shadow-1-strong mb-3">
                                    <?php echo view('components/datetime', ['timestamp' => $article->updated]); ?>
                                </span>
                            <?php endif; ?>

                            <a href="<?php echo e(route('module', ['module' => $module_name, 'action' => 'ShowNews', 'news_id' => $article->news_id, 'tree' => $tree->name()])); ?>">
                                <h4>
                                    <strong><?php echo $article->subject; ?></strong>
                                </h4>
                            </a>
                            <p class="text-muted">
                                <?php
                                if (!empty($article->brief)) {
                                    echo $article->brief;
                                } else {
                                    echo $article->body;
                                }
                                ?>
                            </p>

                            <?php if (Auth::isManager($tree)) : ?>
                                <hr />
                                <form method="post" action="<?php echo e(route('module', ['module' => $module_name, 'action' => 'DeleteNews', 'news_id' => $article->news_id, 'tree' => $tree->name()])); ?>">
                                    <a class="btn btn-link" href="<?php echo e(route('module', ['module' => $module_name, 'action' => 'EditNews', 'news_id' => $article->news_id, 'tree' => $tree->name()])); ?>">
                                        <?php echo I18N::translate('Edit'); ?>
                                    </a>

                                    <button class="btn btn-link" type="submit" data-wt-confirm="<?php echo I18N::translate('Are you sure you want to delete “%s”?', e($article->subject)); ?>" onclick="return confirm(this.dataset.confirm);">
                                        <?php echo I18N::translate('Delete'); ?>
                                    </button>
                                    <?php echo csrf_field(); ?>
                                </form>
                            <?php endif; ?>
                        </div>

                    <?php endforeach; ?>

                    <?php include __DIR__ . '/pagination.php'; ?>
                </div>
            </div>
        </div>
    </div>
</div>

<button type="button" class="btn btn-danger btn-floating btn-lg" id="btn-back-to-top"> <i class="fas fa-arrow-up"></i></button>

<style>
    #btn-back-to-top {
        position: fixed;
        bottom: 20px;
        right: 20px;
        display: none;
    }
</style>

<script>
    let mybutton = document.getElementById("btn-back-to-top");
    window.onscroll = function() {
        scrollFunction();
    };

    function scrollFunction() {
        if (
            document.body.scrollTop > 700 ||
            document.documentElement.scrollTop > 700
        ) {
            mybutton.style.display = "block";
        } else {
            mybutton.style.display = "none";
        }
    }

    mybutton.addEventListener("click", backToTop);

    function backToTop() {
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
    }
</script>