<?php

declare(strict_types=1);

use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\Timestamp;
use Fisharebest\Webtrees\Registry;

/**
 * @var string $body
 * @var string $subject
 * @var string $title
 * @var string $brief
 * @var Tree   $tree
 */

?>

<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-8">
        <div class="card wt-block">
          <div class="card-body">
            <!-- Title -->
            <div class="text-center mb-3">
              <h3 class="wt-page-title text-center fw-bold mt-2 mb-3"><?php echo e($subject) ?></h3>
            </div>

            <!-- Media -->
            <div class="bg-image hover-overlay ripple rounded-0" data-mdb-ripple-color="light">
              <!--full tag -->
              <?php if (isset($news_media)) {
                echo $news_media->displayImage(1000, 667, 'contain', ['class' => 'p-4 rounded-5 w-100 me-3']);
              }
              ?>
              <a href="#!">
                <div class="mask" style="background-color: rgba(251, 251, 251, 0.2)"></div>
              </a>
            </div>

            <!-- Datetime news -->
            <div class="row mt-0">
              <div class="col-12" style="display: inline-block;">
                <?php if ($updated->format('Y-m-d H:i:s') >= date('Y-m-d H:i:s')) : ?>
                  <span class="badge bg-warning px-2 py-1 shadow-1-strong" style="margin-right: 4px;">
                    <?php echo I18N::translate('Planned:') ?> <?php echo view('components/datetime', ['timestamp' => Registry::timestampFactory()->make($updated->getTimestamp())]) ?>
                  </span>
                <?php else : ?>
                  <span class="badge bg-primary px-2 py-1 shadow-1-strong" style="margin-right: 4px;">
                    <?php echo view('components/datetime', ['timestamp' => Registry::timestampFactory()->make($updated->getTimestamp())]); ?>
                  </span>
                <?php endif; ?>

                <?php if (isset($is_pinned) && $is_pinned): ?>
                  <span class="badge bg-danger px-2 py-1 shadow-1-strong" style="margin-right: 4px;">
                    <?php echo I18N::translate('Pinned'); ?>
                  </span>
                <?php endif; ?>

                <?php if ($module->canEditNews($tree)): ?>
                  <a class="btn btn-link p-0" style="margin-right: 4px;" href="<?php echo e(route('module', ['module' => $module_name, 'action' => 'TogglePinned', 'news_id' => $news_id, 'tree' => $tree->name()])) ?>">
                    <?php if ($is_pinned): ?>
                      <i class="bi bi-pin-angle-fill text-danger"></i>
                    <?php else: ?>
                      <i class="bi bi-pin-angle"></i>
                    <?php endif; ?>
                  </a>
                <?php endif; ?>
                
                <?php if (isset($category_id) && $category_id): ?>
                  <?php foreach ($categories as $category): ?>
                    <?php if ($category->getCategoryId() === $category_id): ?>
                      <a href="<?php echo e(route('module', ['module' => $module_name, 'action' => 'Category', 'category_id' => $category->getCategoryId(), 'tree' => $tree->name()])); ?>" class="badge bg-secondary px-2 py-1 text-decoration-none" style="margin-right: 4px;">
                        <?php echo e($category->getName(\Fisharebest\Webtrees\I18N::languageTag())); ?>
                      </a>
                    <?php endif; ?>
                  <?php endforeach; ?>
                <?php endif; ?>
              </div>
            </div>

            <!-- Author -->
            <?php if ($module->showAuthor() && isset($author_user_id) && $author_user_id): ?>
              <div class="mb-3">
                <span class="text-muted"><?php echo I18N::translate('Author:'); ?></span>
                <a href="<?php echo e(route('module', ['module' => $module_name, 'action' => 'Author', 'user_id' => $author_user_id, 'tree' => $tree->name()])); ?>" class="text-decoration-none">
                  <?php if (isset($author_individual) && $author_individual): ?>
                    <?php echo strip_tags($author_individual->fullName()); ?>
                  <?php else: ?>
                    <?php echo e($author); ?>
                  <?php endif; ?>
                </a>
              </div>
            <?php endif; ?>

            <!-- Body news -->
            <div class="card-body">
              <div class="d-flex justify-content-between mb-3">
                <div>
                  <p><?php echo html_entity_decode($brief) ?></p>
                  <p><?php echo html_entity_decode($body) ?></p>
                </div>
              </div>

              <?php if ($module->canEditNews($tree)) : ?>
                <hr />
                <form method="post" action="<?php echo e(route('module', ['module' => $module_name, 'action' => 'DeleteNews', 'news_id' => $news_id, 'tree' => $tree->name()])) ?>">
                  <a class="btn btn-link" href="<?php echo e(route('module', ['module' => $module_name, 'action' => 'EditNews', 'news_id' => $news_id, 'tree' => $tree->name()])) ?>">
                    <?php echo I18N::translate('Edit') ?>
                  </a>

                  <a class="btn btn-link" href="<?php echo e(route('module', ['module' => $module_name, 'action' => 'TogglePinned', 'news_id' => $news_id, 'tree' => $tree->name()])) ?>">
                    <?php if ($is_pinned): ?>
                      <i class="bi bi-pin-angle-fill text-danger"></i> <?php echo I18N::translate('Unpin') ?>
                    <?php else: ?>
                      <i class="bi bi-pin-angle"></i> <?php echo I18N::translate('Pin') ?>
                    <?php endif; ?>
                  </a>

                  <button class="btn btn-link" type="submit" data-wt-confirm="<?php echo I18N::translate('Are you sure you want to delete "%s"?', e($subject)) ?>" onclick="return confirm('<?php echo I18N::translate('Are you sure you want to delete "%s"?', e($subject)) ?>');">
                    <?php echo I18N::translate('Delete') ?>
                  </button>

                  <?php echo csrf_field() ?>
                </form>
              <?php endif; ?>
            </div>

            <!-- Reactions -->
            <div class="card-body">
              <div class="d-flex justify-content-between text-center border-top border-bottom mb-4">
                <div class="d-flex align-items-center">
                  <button type="button" class="btn btn-link btn-lg" data-mdb-ripple-color="dark">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-square-dots" viewBox="0 0 16 16">
                      <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
                      <path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z" />
                    </svg>
                    <?php echo I18N::plural('%s comment', '%s comments', $total_comments, $total_comments); ?>
                  </button>
                  
                  <?php if (isset($view_count)): ?>
                    <button type="button" class="btn btn-link btn-lg" data-mdb-ripple-color="dark">
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
                        <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                        <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                      </svg>
                      <?php echo I18N::plural('%s view', '%s views', $view_count, $view_count); ?>
                    </button>
                  <?php endif; ?>
                </div>

                <a id="like-button" class="btn btn btn-outline-danger" href="javascript:void(0);" data-news-id="<?php echo e($news_id) ?>" data-liked="<?php echo e($like_exists != 0) ?>">
                  <?php if (e($like_exists != 0)) : ?>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
                      <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
                    </svg>
                  <?php else : ?>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                      <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"></path>
                    </svg>
                  <?php endif; ?>
                  <span id="like-count"><?php echo e($total_likes) ?></span>
                </a>
              </div>

              <?php if ($module->canViewComments($tree)) : ?>

                <?php 
                // Используем лимит комментариев из настроек
                $limit_comments = intval($limit_comments ?? 5);
                ?>

                <?php foreach ($comments as $n => $com) : ?>
                  <div class="card-body border-bottom p-2 comment-item <?php echo $n >= $limit_comments ? 'hidden-comment' : '' ?>">
                    <div class="d-flex">
                      <?php
                      if ($com->getIndividual()) {
                        echo $com->getIndividual()->displayImage(50, 50, 'crop', ['class' => 'rounded-circle me-2']);
                      } else {
                        echo '<div style="width: 50px; height: 50px; background: #83A7C9; border-radius: 50%;" class="me-2"></div>';
                      }
                      ?>
                      <div class="w-100">
                        <div class="d-flex justify-content-between">
                          <h6 class="mb-0"><?php echo $com->getRealName() ?></h6>
                          <small class="text-muted"><?php echo view('components/datetime-diff', ['timestamp' => Registry::timestampFactory()->make($com->getUpdated()->getTimestamp())]) ?></small>
                        </div>
                        <p class="mb-1"><?php echo $com->getComment() ?></p>
                        <div class="d-flex align-items-center">
                          <a class="btn btn-sm me-2 p-0" href="javascript:void(0);" data-comments-id="<?php echo e($com->getCommentsId()) ?>" data-liked="<?php echo e($com->isLikeExists()) ?>">
                            <?php if (e($com->isLikeExists())) : ?>
                              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z" />
                              </svg>
                            <?php else : ?>
                              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
                                <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"></path>
                              </svg>
                            <?php endif; ?>
                            <?php if ($com->getLikesCount() > 0) : ?>
                              <span class="ms-1"><?php echo e($com->getLikesCount()) ?></span>
                            <?php endif; ?>
                          </a>
                          
                          <?php if ($module->canEditNews($tree)) : ?>
                            <form method="post" action="<?php echo e(route('module', ['module' => $module_name, 'action' => 'DeleteComments', 'news_id' => $news_id, 'comments_id' => $com->getCommentsId(), 'tree' => $tree->name()])) ?>">
                              <button class="btn btn-sm p-0 text-danger" type="submit" style="margin-top: -7px;" data-wt-confirm="<?php echo I18N::translate('Are you sure you want to delete "%s"?', e($com->getComment())) ?>" onclick="return confirm('<?php echo I18N::translate('Are you sure you want to delete "%s"?', e($com->getComment())) ?>');">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                  <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z" />
                                </svg>
                              </button>
                              <?php echo csrf_field() ?>
                            </form>
                          <?php endif; ?>
                        </div>
                      </div>
                    </div>
                  </div>
                <?php endforeach; ?>

                <?php if (count($comments) > $limit_comments) : ?>
                  <div class="text-center mt-2">
                    <button id="show-all-comments" class="btn btn-primary">
                      <?php echo I18N::translate('Show All'); ?> 
                      (<?php echo count($comments) - $limit_comments; ?> <?php echo I18N::translate('more'); ?>)
                    </button>
                   </div>
                <?php endif; ?>

                <!-- Comment submission form -->
                <?php if ($module->canAddComments($tree)) : ?>
                <div class="mt-3">
                  <form method="post">
                    <div class="d-flex mb-3 align-items-start">
                      <div style="padding-left: 8px; padding-right: 10px;">
                        <?php
                        if (isset($individual1)) {
                          echo $individual1->displayImage(50, 50, 'crop', ['class' => 'rounded-circle']);
                        } else {
                          echo '<div style="width: 50px; height: 50px; background: #83A7C9; border-radius: 50%;"></div>';
                        }
                        ?>
                      </div>
                      <div class="form-outline w-100">
                        <textarea class="form-control" id="comment" name="comment" rows="2" placeholder="<?php echo I18N::translate('Write a comment') ?>"></textarea>
                      </div>
                    </div>
                    <div class="d-flex justify-content-end">
                      <button class="btn btn-primary" type="submit">
                        <?php echo I18N::translate('Send') ?>
                      </button>
                    </div>
                    <?php echo csrf_field() ?>
                  </form>
                </div>
                <?php endif; ?>
              <?php endif; ?>


            </div>
          </div>
        </div>
      </div>

      <!-- Recent news -->
      <div class="col-sm-4">
        <div class="card wt-block">
          <div class="card-body">

            <h3 class="wt-page-title text-center fw-bold mt-2 mb-3"><?php echo I18N::translate('Latest news') ?></h3>
            <?php foreach (
              $articles as $n =>
              $article
            ) : ?>
              <?php if ($article->getNewsId() != $news_id) : ?>
              <div class="row mb-4 border-bottom pb-2">
                <div class="col-3">
                  <?php if ($article->getMedia($tree)) {
                    echo $article->getMedia($tree)->displayImage(100, 67, 'crop', ['class' => 'img-fluid shadow-1-strong rounded w-100']);
                  } ?>
                </div>

                <div class="col-9">
                  <a href="<?php echo e(route('module', ['module' => $module_name, 'action' => 'ShowNews', 'news_id' => $article->getNewsId(), 'tree' => $tree->name()])) ?>">
                    <p class="mb-2"><strong><?php echo $article->getSubject() ?></strong></p>
                    <p>
                      <u><?php echo view('components/datetime', ['timestamp' =>
                          Registry::timestampFactory()->make($article->getUpdated()->getTimestamp())]) ?></u>
                    </p>
                  </a>
                </div>
              </div>
              <?php endif; ?>
            <?php endforeach; ?>
          </div>
        </div>
        
        <!-- Popular news -->
        <?php if (!empty($popular_articles)) : ?>
        <div class="card wt-block mt-4">
          <div class="card-body">
            <h3 class="wt-page-title text-center fw-bold mt-2 mb-3"><?php echo I18N::translate('Popular News') ?></h3>
            <?php foreach ($popular_articles as $article) : ?>
              <?php if ($article->getNewsId() != $news_id) : ?>
              <div class="row mb-4 border-bottom pb-2">
                <div class="col-3">
                  <?php if ($article->getMedia($tree)) {
                    echo $article->getMedia($tree)->displayImage(100, 67, 'crop', ['class' => 'img-fluid shadow-1-strong rounded w-100']);
                  } ?>
                </div>

                <div class="col-9">
                  <a href="<?php echo e(route('module', ['module' => $module_name, 'action' => 'ShowNews', 'news_id' => $article->getNewsId(), 'tree' => $tree->name()])) ?>">
                    <p class="mb-2"><strong><?php echo $article->getSubject() ?></strong></p>
                    <p>
                      <u><?php echo view('components/datetime', ['timestamp' =>
                          Registry::timestampFactory()->make($article->getUpdated()->getTimestamp())]) ?></u>
                    </p>
                  </a>
                </div>
              </div>
              <?php endif; ?>
            <?php endforeach; ?>
          </div>
        </div>
        <?php endif; ?>
      </div>
    </div>
  </div>
</section>

<?php View::push('news-menu.css') ?>
<?php View::endpush() ?>
<?php View::push('javascript') ?>
<script type="application/javascript" id="news-like">
  $(document).ready(function() {
    $('#like-button').on('click', function() {
      var $this = $(this);
      var newsId = $this.data('news-id');
      var isLiked = $this.data('liked');

      if (isLiked) {
        alert('<?php echo I18N::translate('You have already put a like') ?>');
        return;
      }

      $.ajax({
        url: '<?php echo e(route('module', ['module' => $module_name, 'action' => 'LikeNews', 'news_id' => $news_id, 'tree' => $tree->name()])) ?>',
        type: 'GET',
        data: {
          news_id: newsId
        },
        success: function(response) {
          $('#like-count').text(response.data.total_likes);
          $this.data('liked', true);
          $this.html('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/></svg> <span id="like-count">' + response.data.total_likes + '</span>');
        },
        error: function() {
          alert('<?php echo I18N::translate('An error occurred while sending the request') ?>');
        }
      });
    });
    
    // Показать все комментарии без перезагрузки
    $('#show-all-comments').on('click', function() {
      $('.hidden-comment').fadeIn(300);
      $(this).fadeOut(300);
    });
  });
</script>

<script type="application/javascript" id="com-like">
  $(document).ready(function() {
    $('.btn[data-comments-id]').on('click', function() {
      var $this = $(this);
      var commentsId = $this.data('comments-id');
      var isLiked = $this.data('liked');

      if (isLiked) {
        alert('<?php echo I18N::translate('You have already put a like') ?>');
        return;
      }

      $.ajax({
        url: '<?php echo e(route('module', ['module' => $module_name, 'action' => 'LikeComments', 'news_id' => $news_id, 'tree' => $tree->name()])) ?>',
        type: 'GET',
        data: {
          comments_id: commentsId
        },
        success: function(response) {
          $this.find('span').text(response.data.likes_count);
          $this.data('liked', true);
          $this.html('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/></svg> <span class="ms-1">' + response.data.likes_count + '</span>');
        },
        error: function() {
          alert('<?php echo I18N::translate('An error occurred while sending the request') ?>');
        }
      });
    });
  });
</script>



<?php View::endpush() ?>
<style>
  .avatar-block {
    width: 60px;
    height: 60px;
    margin-right: 10px;
  }
  .hidden-comment {
    display: none;
  }
</style>

<button type="button" class="btn btn-danger btn-floating btn-lg" id="btn-back-to-top">
    <i class="fa fa-arrow-up"></i>
    <?php echo I18N::translate('Back to top'); ?>
</button>

<style>
    #btn-back-to-top {
        position: fixed;
        bottom: 20px;
        right: 20px;
        display: none;
        z-index: 1000;
    }
</style>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        let mybutton = document.getElementById("btn-back-to-top");
        
        window.onscroll = function() {
            scrollFunction();
        };

        function scrollFunction() {
            if (
                document.body.scrollTop > 300 ||
                document.documentElement.scrollTop > 300
            ) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
        }

        mybutton.addEventListener("click", backToTop);

        function backToTop() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    });
</script>
