<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Escriure un comentari',
    'Latest news' => 'Últimes notícies',
    'Have you already put a like' => 'Ja has posat un m\'agrada?',
    'Add new media object' => 'Afegir un nou objecte multimèdia',
    'Photo (enter the name of the previously added media file)' => 'Foto (ingresse el nom de l\'arxiu multimèdia agregat prèviament)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s comentari' . I18N::PLURAL . '%s comentaris',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Agregar un element extra al menú principal com a enllaç a una notícia de webtrees.',
    'Comment added' => 'Comentari afegit',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'L\'orde del mòdul de notícies en el menú del lloc (establisca el valor desitjat, de manera predeterminada -1)',
    'Number of news items displayed' => 'Nombre d\'elements de notícies mostrats',
    'Number of comments displayed' => 'Nombre de comentaris mostrats',
    'Settings for the module' => 'Configuració del mòdul',
    'Planned:' => 'Planificat:',  
    'UTC date and time' => 'Data i hora UTC',
    'Are you sure you want to delete "%s"?' => 'Està segur que desitja eliminar "%s"?',
    'Send' => 'Enviar',
    'An error occurred while sending the request' => 'Es va produir un error en enviar la sol·licitud',
    'General Settings' => 'Configuració general',
    'News' => 'Notícies',
    'Add a news article' => 'Afegir un article de notícies',
    'No news articles have been submitted.' => 'No s\'han enviat articles de notícies.',
    'Pinned' => 'Fixat',
    'Edit' => 'Editar',
    'Unpin' => 'Desfaixar',
    'Pin' => 'Fixar',
    'Delete' => 'Eliminar',
    'Categories' => 'Categories',
    'All news' => 'Totes les notícies',
    'Popular News' => 'Notícies populars',
    'Category Management' => 'Gestió de categories',
    'Add New Category' => 'Afegir nova categoria',
    'Category Name' => 'Nom de la categoria',
    'Description' => 'Descripció',
    'Sort Order' => 'Ordre',
    'Add Category' => 'Afegir categoria',
    'Existing Categories' => 'Categories existents',
    'Actions' => 'Accions',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => 'Està segur que desitja eliminar aquesta categoria? Totes les notícies en aquesta categoria romandran però es marcaran com sense categoria.',
    'No categories have been created yet.' => 'Encara no s\'han creat categories.',
    'Minimum views for popular news' => 'Visualitzacions mínimes per a notícies populars',
    'save' => 'guardar',
    '%s view' . I18N::PLURAL . '%s views' => '%s vista' . I18N::PLURAL . '%s vistes',
    'Show All' => 'Mostrar totes',
    'more' => 'més',
    'Back to top' => 'Tornar a dalt',
    'Settings' => 'Configuració',
    'No category' => 'Sense categoria', 
    'Pin to top' => 'Fixar a dalt',
    'Pin this news to the top of the list' => 'Fixar aquesta notícia a la part superior de la llista',
    'Category' => 'Categoria',
    'Title' => 'Títol',
    'Content' => 'Contingut',
    'cancel' => 'cancel·lar',
]; 