<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Napište komentář',
    'Latest news' => 'Nejnovější zprávy',
    'Have you already put a like' => 'Už jste dali like',
    'Add new media object' => 'Přidat nový mediální objekt',
    'Photo (enter the name of the previously added media file)' => 'Fotografie (zadejte název dříve přidaného mediálního souboru)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s komentář' . I18N::PLURAL . '%s komentáře' . I18N::PLURAL . '%s komentářů',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Přidejte do hlavního menu další položku jako odkaz na zprávy webtrees.',
    'Comment added' => 'Komentář přidán',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'Pořadí modulu zpráv v menu webu (nastavte hodnotu na požadovanou, ve výchozím nastavení -1)',
    'Number of news items displayed' => 'Počet zobrazených zpráv',
    'Number of comments displayed' => 'Počet zobrazených komentářů',
    'Settings for the module' => 'Nastavení modulu',
    'Planned:' => 'Plánováno:',  
    'UTC date and time' => 'Datum a čas UTC', 
    'Are you sure you want to delete "%s"?' => 'Opravdu chcete smazat "%s"?',
    'Send' => 'Odeslat',
    'An error occurred while sending the request' => 'Při odesílání požadavku došlo k chybě',
    'General Settings' => 'Obecná nastavení',
    'News' => 'Zprávy',
    'Add a news article' => 'Přidat zprávu',
    'No news articles have been submitted.' => 'Nebyly odeslány žádné zprávy.',
    'Pinned' => 'Připnuté',
    'Edit' => 'Upravit',
    'Unpin' => 'Odepnout',
    'Pin' => 'Připnout',
    'Delete' => 'Smazat',
    'Categories' => 'Kategorie',
    'All news' => 'Všechny zprávy',
    'Popular News' => 'Populární zprávy',
    'Category Management' => 'Správa kategorií',
    'Add New Category' => 'Přidat novou kategorii',
    'Category Name' => 'Název kategorie',
    'Description' => 'Popis',
    'Sort Order' => 'Pořadí řazení',
    'Add Category' => 'Přidat kategorii',
    'Existing Categories' => 'Existující kategorie',
    'Actions' => 'Akce',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => 'Opravdu chcete smazat tuto kategorii? Všechny zprávy v této kategorii zůstanou, ale budou označeny jako nekategorizované.',
    'No categories have been created yet.' => 'Zatím nebyly vytvořeny žádné kategorie.',
    'Minimum views for popular news' => 'Minimální počet zobrazení pro populární zprávy',
    'save' => 'uložit',
    '%s view' . I18N::PLURAL . '%s views' => '%s zobrazení' . I18N::PLURAL . '%s zobrazení' . I18N::PLURAL . '%s zobrazení',
    'Show All' => 'Zobrazit vše',
    'more' => 'více',
    'Back to top' => 'Zpět nahoru',
]; 