<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Schreibe einen Kommentar',
    'Latest news' => 'Aktuelle Neuigkeiten',
    'Have you already put a like' => 'Schon geliked?',
    'Add new media object' => 'Füge ein neues Medienobjekt hinzu',
    'Photo (enter the name of the previously added media file)' => 'Foto (gebe den Namen der zuvor hinzugefügten Mediendatei ein)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s Kommentar' . I18N::PLURAL . '%s Kommentare',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Füge dem Hauptmenü ein zusätzliches Element als Link zu einer Stammbaum Neuigkeit hinzu.',
    'Comment added' => 'Kommentar hinzugefügt',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'Die Reihenfolge des Nachrichtenmoduls im Website-Menü (Setze den gewünschten Wert, Standardwert -1)',
    'Number of news items displayed' => 'Anzahl der angezeigten Neuigkeiten',
    'Number of comments displayed' => 'Anzahl der angezeigten Kommentare',
    'Settings for the module' => 'Einstellungen für das Modul',
    'Planned:' => 'Geplant:',  
    'UTC date and time' => 'UTC-Datum und -Zeit', 
    'Are you sure you want to delete "%s"?' => 'Sind Sie sicher, dass Sie "%s" löschen möchten?',
    'Send' => 'Senden',
    'An error occurred while sending the request' => 'Bei der Übermittlung der Anfrage ist ein Fehler aufgetreten',
    'General Settings' => 'Allgemeine Einstellungen',
    'News' => 'Neuigkeiten',
    'Add a news article' => 'Einen Nachrichtenartikel hinzufügen',
    'No news articles have been submitted.' => 'Es wurden keine Nachrichtenartikel eingereicht.',
    'Pinned' => 'Angeheftet',
    'Edit' => 'Bearbeiten',
    'Unpin' => 'Abheften',
    'Pin' => 'Anheften',
    'Delete' => 'Löschen',
    'Categories' => 'Kategorien',
    'All news' => 'Alle Neuigkeiten',
    'Popular News' => 'Beliebte Neuigkeiten',
    'Category Management' => 'Kategorienverwaltung',
    'Add New Category' => 'Neue Kategorie hinzufügen',
    'Category Name' => 'Kategoriename',
    'Description' => 'Beschreibung',
    'Sort Order' => 'Sortierreihenfolge',
    'Add Category' => 'Kategorie hinzufügen',
    'Existing Categories' => 'Bestehende Kategorien',
    'Actions' => 'Aktionen',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => 'Sind Sie sicher, dass Sie diese Kategorie löschen möchten? Alle Neuigkeiten in dieser Kategorie bleiben erhalten, werden aber als nicht kategorisiert markiert.',
    'No categories have been created yet.' => 'Es wurden noch keine Kategorien erstellt.',
    'Minimum views for popular news' => 'Mindestaufrufe für beliebte Neuigkeiten',
    'save' => 'speichern',
    '%s view' . I18N::PLURAL . '%s views' => '%s Ansicht' . I18N::PLURAL . '%s Ansichten',
    'Show All' => 'Alle anzeigen',
    'more' => 'mehr',
    'Back to top' => 'Nach oben',
];
