<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Write a comment',
    'Latest news' => 'Latest news',
    'Have you already put a like' => 'Have you already put a like',
    'Add new media object' => 'Add new media object',
    'Photo (enter the name of the previously added media file)' => 'Photo (enter the name of the previously added media file)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s comment' . I18N::PLURAL . '%s comments',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Add an extra item to the main menu as a link to a webtrees news.',
    'Comment added' => 'Comment added',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'The order of the news module in the site menu (set the value to the desired, by default -1)',
    'Number of news items displayed' => 'Number of news items displayed',
    'Number of comments displayed' => 'Number of comments displayed',
    'Settings for the module' => 'Settings for the module',
    'Planned:' => 'Planned:',  
    'UTC date and time' => 'UTC date and time', 
    'Are you sure you want to delete "%s"?' => 'Are you sure you want to delete "%s"?',
    'Send' => 'Send',
    'An error occurred while sending the request' => 'An error occurred while sending the request',
    'General Settings' => 'General Settings',
    'News' => 'News',
    'Add a news article' => 'Add a news article',
    'No news articles have been submitted.' => 'No news articles have been submitted.',
    'Pinned' => 'Pinned',
    'Edit' => 'Edit',
    'Unpin' => 'Unpin',
    'Pin' => 'Pin',
    'Delete' => 'Delete',
    'Categories' => 'Categories',
    'All news' => 'All news',
    'Popular News' => 'Popular News',
    'Category Management' => 'Category Management',
    'Add New Category' => 'Add New Category',
    'Category Name' => 'Category Name',
    'Description' => 'Description',
    'Sort Order' => 'Sort Order',
    'Add Category' => 'Add Category',
    'Existing Categories' => 'Existing Categories',
    'Actions' => 'Actions',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => 'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.',
    'No categories have been created yet.' => 'No categories have been created yet.',
    'Minimum views for popular news' => 'Minimum views for popular news',
    'save' => 'save',
    '%s view' . I18N::PLURAL . '%s views' => '%s view' . I18N::PLURAL . '%s views',
    'Show All' => 'Show All',
    'more' => 'more',
    'Back to top' => 'Back to top',
];
