<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Escribir un comentario',
    'Latest news' => 'Últimas noticias',
    'Have you already put a like' => '¿Ya ha puesto un "me gusta"?',
    'Add new media object' => 'Añadir nuevo objeto multimedia',
    'Photo (enter the name of the previously added media file)' => 'Foto (introduzca el nombre del archivo multimedia añadido previamente)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s comentario' . I18N::PLURAL . '%s comentarios',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Añadir un elemento adicional al menú principal como enlace a las noticias de webtrees.',
    'Comment added' => 'Comentario añadido',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'El orden del módulo de noticias en el menú del sitio (establezca el valor deseado, por defecto -1)',
    'Number of news items displayed' => 'Número de noticias mostradas',
    'Number of comments displayed' => 'Número de comentarios mostrados',
    'Settings for the module' => 'Configuración del módulo',
    'Planned:' => 'Planificado:',
    'UTC date and time' => 'Fecha y hora UTC',
    'Are you sure you want to delete "%s"?' => '¿Está seguro de que desea eliminar "%s"?',
    'Send' => 'Enviar',
    'An error occurred while sending the request' => 'Se produjo un error al enviar la solicitud',
    'General Settings' => 'Configuración general',
    'News' => 'Noticias',
    'Add a news article' => 'Añadir un artículo de noticias',
    'No news articles have been submitted.' => 'No se han enviado artículos de noticias.',
    'Pinned' => 'Fijado',
    'Edit' => 'Editar',
    'Unpin' => 'Desfijar',
    'Pin' => 'Fijar',
    'Delete' => 'Eliminar',
    'Categories' => 'Categorías',
    'All news' => 'Todas las noticias',
    'Popular News' => 'Noticias populares',
    'Category Management' => 'Gestión de categorías',
    'Add New Category' => 'Añadir nueva categoría',
    'Category Name' => 'Nombre de categoría',
    'Description' => 'Descripción',
    'Sort Order' => 'Orden de clasificación',
    'Add Category' => 'Añadir categoría',
    'Existing Categories' => 'Categorías existentes',
    'Actions' => 'Acciones',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => '¿Está seguro de que desea eliminar esta categoría? Todas las noticias de esta categoría permanecerán pero se marcarán como sin categoría.',
    'No categories have been created yet.' => 'Aún no se han creado categorías.',
    'Minimum views for popular news' => 'Vistas mínimas para noticias populares',
    'save' => 'guardar',
    '%s view' . I18N::PLURAL . '%s views' => '%s vista' . I18N::PLURAL . '%s vistas',
    'Show All' => 'Mostrar todo',
    'more' => 'más',
    'Back to top' => 'Volver arriba',
    'Settings' => 'Configuración',
    'No category' => 'Sin categoría',
    'Pin to top' => 'Fijar en la parte superior',
    'Pin this news to the top of the list' => 'Fijar esta noticia en la parte superior de la lista',
    'Category' => 'Categoría',
    'Title' => 'Título',
    'Content' => 'Contenido',
    'cancel' => 'cancelar',
];
