<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Escribir un comentario',
    'Latest news' => 'Últimas noticias',
    'Have you already put a like' => '¿Ya pusiste un "me gusta"?',
    'Add new media object' => 'Agregar un nuevo objeto multimedia',
    'Photo (enter the name of the previously added media file)' => 'Foto (ingrese el nombre del archivo multimedia agregado previamente)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s comentario' . I18N::PLURAL . '%s comentarios',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Agregar un elemento extra al menú principal como enlace a una noticia de webtrees.',
    'Comment added' => 'Comentario agregado',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'El orden del módulo de noticias en el menú del sitio (establezca el valor en el deseado, de forma predeterminada -1)',
    'Number of news items displayed' => 'Número de elementos de noticias mostrados',
    'Number of comments displayed' => 'Número de comentarios mostrados',
    'Settings for the module' => 'Configuración del módulo',
    'Planned:' => 'Planificado:',  
    'UTC date and time' => 'Fecha y hora UTC',
    'Are you sure you want to delete "%s"?' => '¿Está seguro de que desea eliminar "%s"?',
    'Send' => 'Enviar',
    'An error occurred while sending the request' => 'Se produjo un error al enviar la solicitud',
    'General Settings' => 'Configuración general',
    'News' => 'Noticias',
    'Add a news article' => 'Agregar un artículo de noticias',
    'No news articles have been submitted.' => 'No se han enviado artículos de noticias.',
    'Pinned' => 'Fijado',
    'Edit' => 'Editar',
    'Unpin' => 'Desfijar',
    'Pin' => 'Fijar',
    'Delete' => 'Eliminar',
    'Categories' => 'Categorías',
    'All news' => 'Todas las noticias',
    'Popular News' => 'Noticias populares',
    'Category Management' => 'Gestión de categorías',
    'Add New Category' => 'Agregar nueva categoría',
    'Category Name' => 'Nombre de categoría',
    'Description' => 'Descripción',
    'Sort Order' => 'Orden',
    'Add Category' => 'Agregar categoría',
    'Existing Categories' => 'Categorías existentes',
    'Actions' => 'Acciones',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => '¿Está seguro de que desea eliminar esta categoría? Todas las noticias en esta categoría permanecerán pero se marcarán como sin categoría.',
    'No categories have been created yet.' => 'Aún no se han creado categorías.',
    'Minimum views for popular news' => 'Visualizaciones mínimas para noticias populares',
    'save' => 'guardar',
    '%s view' . I18N::PLURAL . '%s views' => '%s vista' . I18N::PLURAL . '%s vistas',
    'Show All' => 'Mostrar todos',
    'more' => 'más',
    'Back to top' => 'Volver arriba',
];
