<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Rédigez un commentaire',
    'Latest news' => 'Dernières nouvelles',
    'Have you already put a like' => 'Avez-vous déjà mis un "j\'aime"',
    'Add new media object' => 'Ajouter un nouvel objet multimédia',
    'Photo (enter the name of the previously added media file)' => 'Photo (entrez le nom du fichier multimédia précédemment ajouté)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s commentaire' . I18N::PLURAL . '%s commentaires',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Ajoutez un élément supplémentaire au menu principal sous forme de lien vers les nouvelles webtrees.',
    'Comment added' => 'Commentaire ajouté',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'L\'ordre du module de nouvelles dans le menu du site (définissez la valeur souhaitée, par défaut -1)',
    'Number of news items displayed' => 'Nombre d\'articles de nouvelles affichés',
    'Number of comments displayed' => 'Nombre de commentaires affichés',
    'Settings for the module' => 'Paramètres pour le module',
    'Planned:' => 'Planifié:', 
    'UTC date and time' => 'Date et heure UTC',
    'Are you sure you want to delete "%s"?' => 'Êtes-vous sûr de vouloir supprimer "%s" ?',
    'Send' => 'Envoyer',
    'An error occurred while sending the request' => 'Une erreur s\'est produite lors de l\'envoi de la demande',
    'General Settings' => 'Paramètres généraux',
    'News' => 'Nouvelles',
    'Add a news article' => 'Ajouter un article de nouvelles',
    'No news articles have been submitted.' => 'Aucun article de nouvelles n\'a été soumis.',
    'Pinned' => 'Épinglé',
    'Edit' => 'Modifier',
    'Unpin' => 'Désépingler',
    'Pin' => 'Épingler',
    'Delete' => 'Supprimer',
    'Categories' => 'Catégories',
    'All news' => 'Toutes les nouvelles',
    'Popular News' => 'Nouvelles populaires',
    'Category Management' => 'Gestion des catégories',
    'Add New Category' => 'Ajouter une nouvelle catégorie',
    'Category Name' => 'Nom de la catégorie',
    'Description' => 'Description',
    'Sort Order' => 'Ordre de tri',
    'Add Category' => 'Ajouter une catégorie',
    'Existing Categories' => 'Catégories existantes',
    'Actions' => 'Actions',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => 'Êtes-vous sûr de vouloir supprimer cette catégorie ? Toutes les nouvelles de cette catégorie resteront mais seront marquées comme non catégorisées.',
    'No categories have been created yet.' => 'Aucune catégorie n\'a encore été créée.',
    'Minimum views for popular news' => 'Nombre minimum de vues pour les nouvelles populaires',
    'save' => 'enregistrer',
    '%s view' . I18N::PLURAL . '%s views' => '%s vue' . I18N::PLURAL . '%s vues',
    'Show All' => 'Afficher tout',
    'more' => 'plus',
    'Back to top' => 'Retour en haut',
];
