<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Skrifaðu umsögn',
    'Latest news' => 'Nýjustu fréttir',
    'Have you already put a like' => 'Ertu búinn að líka við umsögnina',
    'Add new media object' => 'Bæta við nýjum gagnahlut',
    'Photo (enter the name of the previously added media file)' => 'Mynd (sláðu inn heiti á viðbættri gagnaskrá)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s umsögn' . I18N::PLURAL . '%s umsagnir',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Bættu vali við aðalvalmyndina sem tengil á fréttir ættfræðivefsins.',
    'Comment added' => 'Umsögn bætt við',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'Röð fréttaeiningarinnar í valmynd vefsíðunnar (stilltu gildið á æskilegt, sjálfgefið -1)',
    'Number of news items displayed' => 'Fjöldi birtra frétta',
    'Number of comments displayed' => 'Fjöldi ummæla sem birtast',
    'Settings for the module' => 'Stillingar fyrir eininguna',
    'Planned:' => 'Skipulagt:',
    'UTC date and time' => 'UTC dagsetning og tími',
    'Are you sure you want to delete "%s"?' => 'Ertu viss um að þú viljir eyða "%s"?',
    'Send' => 'Senda',
    'An error occurred while sending the request' => 'Villa kom upp við að senda beiðnina',
    'General Settings' => 'Almennar stillingar',
    'News' => 'Fréttir',
    'Add a news article' => 'Bæta við fréttafrásögn',
    'No news articles have been submitted.' => 'Engar fréttir hafa verið sendar inn.',
    'Pinned' => 'Fest',
    'Edit' => 'Breyta',
    'Unpin' => 'Losa',
    'Pin' => 'Festa',
    'Delete' => 'Eyða',
    'Categories' => 'Flokkar',
    'All news' => 'Allar fréttir',
    'Popular News' => 'Vinsælar fréttir',
    'Category Management' => 'Flokkastjórnun',
    'Add New Category' => 'Bæta við nýjum flokki',
    'Category Name' => 'Nafn flokks',
    'Description' => 'Lýsing',
    'Sort Order' => 'Röðun',
    'Add Category' => 'Bæta við flokki',
    'Existing Categories' => 'Núverandi flokkar',
    'Actions' => 'Aðgerðir',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => 'Ertu viss um að þú viljir eyða þessum flokki? Allar fréttir í þessum flokki verða áfram en verða merktar sem óflokkað.',
    'No categories have been created yet.' => 'Engir flokkar hafa verið búnir til ennþá.',
    'Minimum views for popular news' => 'Lágmarks skoðanir fyrir vinsælar fréttir',
    'save' => 'vista',
    '%s view' . I18N::PLURAL . '%s views' => '%s skoðun' . I18N::PLURAL . '%s skoðanir',
    'Show All' => 'Sýna allt',
    'more' => 'fleiri',
    'Back to top' => 'Til baka upp',
    'Settings' => 'Stillingar',
    'No category' => 'Enginn flokkur', 
    'Pin to top' => 'Festa efst',
    'Pin this news to the top of the list' => 'Festa þessa frétt efst á listann',
    'Category' => 'Flokkur',
    'Title' => 'Titill',
    'Content' => 'Efni',
    'cancel' => 'hætta við',
];
