<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Scrivi un commento',
    'Latest news' => 'Ultime notizie',
    'Have you already put a like' => 'Hai già messo "mi piace"',
    'Add new media object' => 'Aggiungi nuovo oggetto multimediale',
    'Photo (enter the name of the previously added media file)' => 'Foto (inserisci il nome del file multimediale aggiunto in precedenza)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s commento' . I18N::PLURAL . '%s commenti',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Aggiungi un elemento aggiuntivo al menu principale come collegamento alle notizie di webtrees.',
    'Comment added' => 'Commento aggiunto',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'L\'ordine del modulo notizie nel menu del sito (imposta il valore desiderato, di default -1)',
    'Number of news items displayed' => 'Numero di notizie visualizzate',
    'Number of comments displayed' => 'Numero di commenti visualizzati',
    'Settings for the module' => 'Impostazioni per il modulo',
    'Planned:' => 'Pianificato:',  
    'UTC date and time' => 'Data e ora UTC', 
    'Are you sure you want to delete "%s"?' => 'Sei sicuro di voler eliminare "%s"?',
    'Send' => 'Invia',
    'An error occurred while sending the request' => 'Si è verificato un errore durante l\'invio della richiesta',
    'General Settings' => 'Impostazioni generali',
    'News' => 'Notizie',
    'Add a news article' => 'Aggiungi un articolo',
    'No news articles have been submitted.' => 'Non sono stati inviati articoli di notizie.',
    'Pinned' => 'In evidenza',
    'Edit' => 'Modifica',
    'Unpin' => 'Rimuovi da evidenza',
    'Pin' => 'Metti in evidenza',
    'Delete' => 'Elimina',
    'Categories' => 'Categorie',
    'All news' => 'Tutte le notizie',
    'Popular News' => 'Notizie popolari',
    'Category Management' => 'Gestione categorie',
    'Add New Category' => 'Aggiungi nuova categoria',
    'Category Name' => 'Nome categoria',
    'Description' => 'Descrizione',
    'Sort Order' => 'Ordinamento',
    'Add Category' => 'Aggiungi categoria',
    'Existing Categories' => 'Categorie esistenti',
    'Actions' => 'Azioni',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => 'Sei sicuro di voler eliminare questa categoria? Tutte le notizie in questa categoria rimarranno ma saranno contrassegnate come non categorizzate.',
    'No categories have been created yet.' => 'Non è stata ancora creata alcuna categoria.',
    'Minimum views for popular news' => 'Visualizzazioni minime per notizie popolari',
    'save' => 'salva',
    '%s view' . I18N::PLURAL . '%s views' => '%s visualizzazione' . I18N::PLURAL . '%s visualizzazioni',
    'Show All' => 'Mostra tutto',
    'more' => 'altro',
    'Back to top' => 'Torna all\'inizio',
    'Settings' => 'Impostazioni',
    'No category' => 'Nessuna categoria',
    'Pin to top' => 'Metti in evidenza in alto',
    'Pin this news to the top of the list' => 'Metti questa notizia in evidenza in cima alla lista',
    'Category' => 'Categoria',
    'Title' => 'Titolo',
    'Content' => 'Contenuto',
    'cancel' => 'annulla',
]; 