<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Schrijf een reactie',
    'Latest news' => 'Laatste nieuws',
    'Have you already put a like' => 'Heb je al een like geplaatst',
    'Add new media object' => 'Nieuw mediaobject toevoegen',
    'Photo (enter the name of the previously added media file)' => 'Foto (voer de naam in van het eerder toegevoegde mediabestand)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s reactie' . I18N::PLURAL . '%s reacties',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Voeg een extra item toe aan het hoofdmenu als link naar een webtreesnieuwsbericht.',
    'Comment added' => 'Reactie toegevoegd',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'De volgorde van de nieuwsmodule in het websitemenu (stel de gewenste waarde in, standaardwaarde -1)',
    'Number of news items displayed' => 'Aantal weergegeven nieuwsberichten',
    'Number of comments displayed' => 'Aantal weergegeven reacties',
    'Settings for the module' => 'Instellingen voor de module',
    'Planned:' => 'Gepland:',  
    'UTC date and time' => 'UTC-datum en -tijd',
    'Are you sure you want to delete "%s"?' => 'Weet u zeker dat u "%s" wilt verwijderen?',
    'Send' => 'Verzenden',
    'An error occurred while sending the request' => 'Er is een fout opgetreden bij het verzenden van het verzoek',
    'General Settings' => 'Algemene instellingen',
    'News' => 'Nieuws',
    'Add a news article' => 'Voeg een nieuwsartikel toe',
    'No news articles have been submitted.' => 'Er zijn geen nieuwsartikelen ingediend.',
    'Pinned' => 'Vastgepind',
    'Edit' => 'Bewerken',
    'Unpin' => 'Losmaken',
    'Pin' => 'Vastpinnen',
    'Delete' => 'Verwijderen',
    'Categories' => 'Categorieën',
    'All news' => 'Alle nieuws',
    'Popular News' => 'Populair nieuws',
    'Category Management' => 'Categoriebeheer',
    'Add New Category' => 'Nieuwe categorie toevoegen',
    'Category Name' => 'Categorienaam',
    'Description' => 'Beschrijving',
    'Sort Order' => 'Sorteervolgorde',
    'Add Category' => 'Categorie toevoegen',
    'Existing Categories' => 'Bestaande categorieën',
    'Actions' => 'Acties',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => 'Weet u zeker dat u deze categorie wilt verwijderen? Alle nieuws in deze categorie blijft behouden maar wordt gemarkeerd als niet-gecategoriseerd.',
    'No categories have been created yet.' => 'Er zijn nog geen categorieën aangemaakt.',
    'Minimum views for popular news' => 'Minimum aantal weergaven voor populair nieuws',
    'save' => 'opslaan',
    '%s view' . I18N::PLURAL . '%s views' => '%s weergave' . I18N::PLURAL . '%s weergaven',
    'Show All' => 'Alles weergeven',
    'more' => 'meer',
    'Back to top' => 'Terug naar boven',
];
