<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Napisz komentarz',
    'Latest news' => 'Najnowsze wiadomości',
    'Have you already put a like' => 'Czy już polubiłeś',
    'Add new media object' => 'Dodaj nowy obiekt multimedialny',
    'Photo (enter the name of the previously added media file)' => 'Zdjęcie (wpisz nazwę wcześniej dodanego pliku multimedialnego)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s komentarz' . I18N::PLURAL . '%s komentarze' . I18N::PLURAL . '%s komentarzy',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Dodaj dodatkową pozycję do menu głównego jako link do wiadomości webtrees.',
    'Comment added' => 'Komentarz dodany',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'Kolejność modułu wiadomości w menu witryny (ustaw wartość na pożądaną, domyślnie -1)',
    'Number of news items displayed' => 'Liczba wyświetlanych wiadomości',
    'Number of comments displayed' => 'Liczba wyświetlanych komentarzy',
    'Settings for the module' => 'Ustawienia modułu',
    'Planned:' => 'Planowane:',  
    'UTC date and time' => 'Data i godzina UTC', 
    'Are you sure you want to delete "%s"?' => 'Czy na pewno chcesz usunąć "%s"?',
    'Send' => 'Wyślij',
    'An error occurred while sending the request' => 'Wystąpił błąd podczas wysyłania żądania',
    'General Settings' => 'Ustawienia ogólne',
    'News' => 'Wiadomości',
    'Add a news article' => 'Dodaj artykuł',
    'No news articles have been submitted.' => 'Nie dodano żadnych artykułów.',
    'Pinned' => 'Przypięte',
    'Edit' => 'Edytuj',
    'Unpin' => 'Odepnij',
    'Pin' => 'Przypnij',
    'Delete' => 'Usuń',
    'Categories' => 'Kategorie',
    'All news' => 'Wszystkie wiadomości',
    'Popular News' => 'Popularne wiadomości',
    'Category Management' => 'Zarządzanie kategoriami',
    'Add New Category' => 'Dodaj nową kategorię',
    'Category Name' => 'Nazwa kategorii',
    'Description' => 'Opis',
    'Sort Order' => 'Kolejność sortowania',
    'Add Category' => 'Dodaj kategorię',
    'Existing Categories' => 'Istniejące kategorie',
    'Actions' => 'Akcje',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => 'Czy na pewno chcesz usunąć tę kategorię? Wszystkie wiadomości w tej kategorii pozostaną, ale zostaną oznaczone jako nieskategoryzowane.',
    'No categories have been created yet.' => 'Nie utworzono jeszcze kategorii.',
    'Minimum views for popular news' => 'Minimalna liczba wyświetleń dla popularnych wiadomości',
    'save' => 'zapisz',
    '%s view' . I18N::PLURAL . '%s views' => '%s wyświetlenie' . I18N::PLURAL . '%s wyświetlenia' . I18N::PLURAL . '%s wyświetleń',
    'Show All' => 'Pokaż wszystko',
    'more' => 'więcej',
    'Back to top' => 'Do góry',
]; 