<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Написать комментарий',
    'Latest news' => 'Последние новости',
    'Have you already put a like' => 'Вы уже поставили лайк',
    'Add new media object' => 'Добавить новый медиобъект',
    'Photo (enter the name of the previously added media file)' => 'Фотография (введите название ранее добавленного медиафайла)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s комментарий' . I18N::PLURAL . '%s комментария' . I18N::PLURAL . '%s комментариев',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'дополнительный пункт в главное меню в качестве ссылки на новости webtrees',
    'Comment added' => 'Комментарий добавлен',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'Порядок расположения новостного модуля в меню сайта (установите желаемое значение, по умолчанию -1)',
    'Number of news items displayed' => 'Количество отображаемых новостей',
    'Number of comments displayed' => 'Количество отображаемых комментариев',
    'Settings for the module' => 'Настройки для модуля',
    'Planned:' => 'Запланировано:',  
    'UTC date and time' => 'Дата и время по UTC', 
    'Are you sure you want to delete "%s"?' => 'Вы уверены, что хотите удалить "%s"?',
    'Send' => 'Отправить',
    'An error occurred while sending the request' => 'Произошла ошибка при отправке запроса',
    'General Settings' => 'Общие настройки',
    'News' => 'Новости',
    'Add a news article' => 'Добавить новость',
    'No news articles have been submitted.' => 'Новости не добавлены.',
    'Pinned' => 'Закреплено',
    'Edit' => 'Редактировать',
    'Unpin' => 'Открепить',
    'Pin' => 'Закрепить',
    'Delete' => 'Удалить',
    'Categories' => 'Категории',
    'All news' => 'Все новости',
    'Popular News' => 'Популярные новости',
    'Category Management' => 'Управление категориями',
    'Add New Category' => 'Добавить новую категорию',
    'Category Name' => 'Название категории',
    'Description' => 'Описание',
    'Sort Order' => 'Порядок сортировки',
    'Add Category' => 'Добавить категорию',
    'Existing Categories' => 'Существующие категории',
    'Actions' => 'Действия',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => 'Вы уверены, что хотите удалить эту категорию? Все новости в этой категории останутся, но будут помечены как без категории.',
    'No categories have been created yet.' => 'Категории еще не созданы.',
    'Minimum views for popular news' => 'Минимальное количество просмотров для популярных новостей',
    'save' => 'сохранить',
    '%s view' . I18N::PLURAL . '%s views' => '%s просмотр' . I18N::PLURAL . '%s просмотра' . I18N::PLURAL . '%s просмотров',
    'Show All' => 'Показать все',
    'more' => 'ещё',
    'Back to top' => 'Наверх',
];


