<?php

use Fisharebest\Webtrees\I18N;

return [
    'Write a comment' => 'Skriv en kommentar',
    'Latest news' => 'Senaste nytt',
    'Have you already put a like' => 'Har du redan gillat',
    'Add new media object' => 'Lägg till nytt medieobjekt',
    'Photo (enter the name of the previously added media file)' => 'Foto (ange namnet på den tidigare tillagda mediefilen)',
    '%s comment' . I18N::PLURAL . '%s comments' => '%s kommentar' . I18N::PLURAL . '%s kommentarer',
    'Add an extra item to the main menu as a link to a webtrees news.' => 'Lägg till en extra post i huvudmenyn som en länk till webtrees nyheter.',
    'Comment added' => 'Kommentar tillagd',
    'The order of the news module in the site menu (set the value to the desired, by default -1)' => 'Ordningen på nyhetsmodulen i sajtmenyn (ställ in värdet på önskat, som standard -1)',
    'Number of news items displayed' => 'Antal visade nyheter',
    'Number of comments displayed' => 'Antal visade kommentarer',
    'Settings for the module' => 'Inställningar för modulen',
    'Planned:' => 'Planerad:',  
    'UTC date and time' => 'UTC datum och tid', 
    'Are you sure you want to delete "%s"?' => 'Är du säker på att du vill ta bort "%s"?',
    'Send' => 'Skicka',
    'An error occurred while sending the request' => 'Ett fel uppstod när begäran skickades',
    'General Settings' => 'Allmänna inställningar',
    'News' => 'Nyheter',
    'Add a news article' => 'Lägg till en nyhetsartikel',
    'No news articles have been submitted.' => 'Inga nyhetsartiklar har skickats in.',
    'Pinned' => 'Fastnålad',
    'Edit' => 'Redigera',
    'Unpin' => 'Ta bort nål',
    'Pin' => 'Nåla fast',
    'Delete' => 'Ta bort',
    'Categories' => 'Kategorier',
    'All news' => 'Alla nyheter',
    'Popular News' => 'Populära nyheter',
    'Category Management' => 'Kategorihantering',
    'Add New Category' => 'Lägg till ny kategori',
    'Category Name' => 'Kategorinamn',
    'Description' => 'Beskrivning',
    'Sort Order' => 'Sorteringsordning',
    'Add Category' => 'Lägg till kategori',
    'Existing Categories' => 'Befintliga kategorier',
    'Actions' => 'Åtgärder',
    'Are you sure you want to delete this category? All news in this category will remain but will be marked as uncategorized.' => 'Är du säker på att du vill ta bort den här kategorin? Alla nyheter i denna kategori kommer att finnas kvar men kommer att markeras som okategoriserade.',
    'No categories have been created yet.' => 'Inga kategorier har skapats ännu.',
    'Minimum views for popular news' => 'Minsta antal visningar för populära nyheter',
    'save' => 'spara',
    '%s view' . I18N::PLURAL . '%s views' => '%s visning' . I18N::PLURAL . '%s visningar',
    'Show All' => 'Visa alla',
    'more' => 'mer',
    'Back to top' => 'Tillbaka till toppen',
    'Settings' => 'Inställningar',
    'No category' => 'Ingen kategori', 
    'Pin to top' => 'Nåla fast högst upp',
    'Pin this news to the top of the list' => 'Nåla fast den här nyheten högst upp i listan',
    'Category' => 'Kategori',
    'Title' => 'Titel',
    'Content' => 'Innehåll',
    'cancel' => 'avbryt',
]; 